server:
  port: 8080

management:
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: 'true'
spring:
  cloud:
    consul:
      discovery:
        instanceId: gateway
        health-check-interval: 5s
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: service-a
        uri: lb://service-a
        predicates:
        - Path=/srva/**
        filters:
        - RewritePath=/srva/(?<segment>.*), /$\{segment}
        - name: CircuitBreaker
          args:
            name: monitor-srvA
            fallbackUri: forward:/fallback/serviceA
      - id: service-b
        uri: lb://ms-service-b
        predicates:
        - Path=/srvb/**
        filters:
        - RewritePath=/srvb/(?<segment>.*), /$\{segment}
        - name: CircuitBreaker
          args:
            name: monitor-srvB
            fallbackUri: forward:/fallback/serviceB